[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
serde = "1.0.176"
sqlx = "0.7.1"
uuid = { version = "1.4.1", features = ["serde"] }
